lab1/CinemaStudio/CinemaStudio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinemaStudio.Models;

namespace CarRentCompany.Controllers
{
    public class HomeController : Controller
    {
        private CinemaStudioModel db = new CinemaStudioModel();

        public ActionResult Index()
        {
            return View();
        }

        #region Вход \ Выход

        public ActionResult SignInPage()
        {
            return View();
        }

        public ActionResult SignOut()
        {
            Response.Cookies["RoleCookie"].Expires = DateTime.Now.AddDays(-1d);

            return RedirectToAction("Index");
        }

        #endregion

        #region  Сохранение cookie для каждого пользователя.

        public ActionResult Client()
        {
            HttpCookie clientcookie = new HttpCookie("RoleCookie");
            clientcookie.Value = "Client";
            Response.Cookies.Add(clientcookie);

            return RedirectToAction("HomeClientPage");
        }

        public ActionResult Employee()
        {
            HttpCookie employeecookie = new HttpCookie("RoleCookie");
            employeecookie.Value = "Employee";
            Response.Cookies.Add(employeecookie);

            return RedirectToAction("HomeEmployeePage");
        }

        public ActionResult Administrator()
        {
            HttpCookie admincookie = new HttpCookie("RoleCookie");
            admincookie.Value = "Admin";
            Response.Cookies.Add(admincookie);

            return RedirectToAction("HomeAdminPage");
        }

        #endregion

        #region Личный кабинет каждого пользователя

        public ActionResult HomeClientPage(Человек model)
        {
            return View(model);
        }

        public ActionResult HomeEmployeePage()
        {
            return View();
        }

        public ActionResult HomeAdminPage()
        {
            return View();
        }

        #endregion
    }
}

lab1/CinemaStudio/CinemaStudio/Controllers/ФильмController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CinemaStudio.Models;

namespace CinemaStudio.Controllers
{
    public class ФильмController : Controller
    {
        private CinemaStudioModel db = new CinemaStudioModel();

        // GET: Фильм
        public ActionResult Index()
        {
            var фильм = db.Фильм.Include(ф => ф.Постпроизводство).Include(ф => ф.Предпроизводство).Include(ф => ф.Съёмочный_период).Include(ф => ф.Тиражирование).Include(ф => ф.Титры_и_субтитры);
            return View(фильм.ToList());
        }

        [HttpPost]
        public ActionResult Index(string genre, int? ageRestriction)
        {
            if (genre == "" || ageRestriction == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var Фильм = db.Фильм
                .Where(a => a.Жанр == genre)
                .Where(a => a.ВозрастноеОграничение == ageRestriction);
            return View(Фильм.ToList());
        }

        // GET: Фильм/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Фильм фильм = db.Фильм.Find(id);
            if (фильм == null)
            {
                return HttpNotFound();
            }
            return View(фильм);
        }

        // GET: Фильм/Create
        public ActionResult Create()
        {
            ViewBag.ID_Постпроизводства = new SelectList(db.Постпроизводство, "ID_Постпроизводства", "Тип_фонограммы");
            ViewBag.ID_Предпроизводства = new SelectList(db.Предпроизводство, "ID_Предпроизводства", "Тема");
            ViewBag.ID_СъемочногоПерида = new SelectList(db.Съёмочный_период, "ID_СъемочногоПерида", "ID_СъемочногоПерида");
            ViewBag.ID_Тиражирования = new SelectList(db.Тиражирование, "ID_Тиражирования", "ID_Тиражирования");
            ViewBag.ID_ТИС = new SelectList(db.Титры_и_субтитры, "ID_ТИС", "Язык_текста");
            return View();
        }

        // POST: Фильм/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Фильма,Название,Дата_релиза,БюджетФильма,Длительность,Язык,Жанр,Рейтинг,ВозрастноеОграничение,Статус,ID_Предпроизводства,ID_СъемочногоПерида,ID_Постпроизводства,ID_ТИС,ID_Тиражирования")] Фильм фильм)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Фильм.Add(фильм);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ID_Постпроизводства = new SelectList(db.Постпроизводство, "ID_Постпроизводства", "Тип_фонограммы", фильм.ID_Постпроизводства);
                ViewBag.ID_Предпроизводства = new SelectList(db.Предпроизводство, "ID_Предпроизводства", "Тема", фильм.ID_Предпроизводства);
                ViewBag.ID_СъемочногоПерида = new SelectList(db.Съёмочный_период, "ID_СъемочногоПерида", "ID_СъемочногоПерида", фильм.ID_СъемочногоПерида);
                ViewBag.ID_Тиражирования = new SelectList(db.Тиражирование, "ID_Тиражирования", "ID_Тиражирования", фильм.ID_Тиражирования);
                ViewBag.ID_ТИС = new SelectList(db.Титры_и_субтитры, "ID_ТИС", "Язык_текста", фильм.ID_ТИС);
                return View(фильм);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Фильм/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Фильм фильм = db.Фильм.Find(id);
            if (фильм == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Постпроизводства = new SelectList(db.Постпроизводство, "ID_Постпроизводства", "Тип_фонограммы", фильм.ID_Постпроизводства);
            ViewBag.ID_Предпроизводства = new SelectList(db.Предпроизводство, "ID_Предпроизводства", "Тема", фильм.ID_Предпроизводства);
            ViewBag.ID_СъемочногоПерида = new SelectList(db.Съёмочный_период, "ID_СъемочногоПерида", "ID_СъемочногоПерида", фильм.ID_СъемочногоПерида);
            ViewBag.ID_Тиражирования = new SelectList(db.Тиражирование, "ID_Тиражирования", "ID_Тиражирования", фильм.ID_Тиражирования);
            ViewBag.ID_ТИС = new SelectList(db.Титры_и_субтитры, "ID_ТИС", "Язык_текста", фильм.ID_ТИС);
            return View(фильм);
        }

        // POST: Фильм/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Фильма,Название,Дата_релиза,БюджетФильма,Длительность,Язык,Жанр,Рейтинг,ВозрастноеОграничение,Статус,ID_Предпроизводства,ID_СъемочногоПерида,ID_Постпроизводства,ID_ТИС,ID_Тиражирования")] Фильм фильм)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(фильм).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_Постпроизводства = new SelectList(db.Постпроизводство, "ID_Постпроизводства", "Тип_фонограммы", фильм.ID_Постпроизводства);
                ViewBag.ID_Предпроизводства = new SelectList(db.Предпроизводство, "ID_Предпроизводства", "Тема", фильм.ID_Предпроизводства);
                ViewBag.ID_СъемочногоПерида = new SelectList(db.Съёмочный_период, "ID_СъемочногоПерида", "ID_СъемочногоПерида", фильм.ID_СъемочногоПерида);
                ViewBag.ID_Тиражирования = new SelectList(db.Тиражирование, "ID_Тиражирования", "ID_Тиражирования", фильм.ID_Тиражирования);
                ViewBag.ID_ТИС = new SelectList(db.Титры_и_субтитры, "ID_ТИС", "Язык_текста", фильм.ID_ТИС);
                return View(фильм);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Фильм/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Фильм фильм = db.Фильм.Find(id);
            if (фильм == null)
            {
                return HttpNotFound();
            }
            return View(фильм);
        }

        // POST: Фильм/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Фильм фильм = db.Фильм.Find(id);
                db.Фильм.Remove(фильм);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab1/CinemaStudio/CinemaStudio/Controllers/ЧеловекController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CinemaStudio.Models;

namespace CinemaStudio.Controllers
{
    public class ЧеловекController : Controller
    {
        private CinemaStudioModel db = new CinemaStudioModel();

        // GET: Человек
        public ActionResult Index()
        {
            return View(db.Человек.ToList());
        }

        [HttpPost]
        public ActionResult Index(string lastName)
        {
            if (lastName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<Человек> people = new List<Человек>();
            people.Add(db.Человек.Where(a => a.Фамилия == lastName).FirstOrDefault());
            foreach (Человек item in db.Человек.Where(a => a.Фамилия != lastName))
            {
                people.Add(item);
            }

            return View(people);
        }

        // GET: Человек/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Человек человек = db.Человек.Find(id);
            if (человек == null)
            {
                return HttpNotFound();
            }
            return View(человек);
        }

        // GET: Человек/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Человек/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Человека,Имя,Фамилия,Отчество,Пол,Образование,Телефон,ДатаРождения,СерияНомерПаспорта")] Человек человек)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Человек.Add(человек);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(человек);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Человек/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Человек человек = db.Человек.Find(id);
            if (человек == null)
            {
                return HttpNotFound();
            }
            return View(человек);
        }

        // POST: Человек/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Человека,Имя,Фамилия,Отчество,Пол,Образование,Телефон,ДатаРождения,СерияНомерПаспорта")] Человек человек)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(человек).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(человек);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Человек/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Человек человек = db.Человек.Find(id);
            if (человек == null)
            {
                return HttpNotFound();
            }
            return View(человек);
        }

        // POST: Человек/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Человек человек = db.Человек.Find(id);
                db.Человек.Remove(человек);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab1/CinemaStudio/CinemaStudio/Views/Home/HomeAdminPage.cshtml
@{
    ViewBag.Title = "Администратор";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="hp-btn-div text-center">
        @Html.ActionLink("Предпроизводство", "Index", "Предпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Съёмочный период", "Index", "Съёмочный_период", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Постпроизводство", "Index", "Постпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Титры и субтитры", "Index", "Титры_и_субтитры", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Тиражирование", "Index", "Тиражирование", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Фильмы", "Index", "Фильм", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Сотрудники", "Index", "Сотрудник", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Люди", "Index", "Человек", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
    </div>
</body>
</html>

lab1/CinemaStudio/CinemaStudio/Views/Home/HomeClientPage.cshtml
@{
    ViewBag.Title = "Клиент";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="hp-btn-div text-center">
        @Html.ActionLink("Предпроизводство", "Index", "Предпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Съёмочный период", "Index", "Съёмочный_период", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Постпроизводство", "Index", "Постпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Титры и субтитры", "Index", "Титры_и_субтитры", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Тиражирование", "Index", "Тиражирование", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Фильмы", "Index", "Фильм", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
    </div>
</body>
</html>


lab1/CinemaStudio/CinemaStudio/Views/Home/HomeEmployeePage.cshtml
@{
    ViewBag.Title = "Сотрудник";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="hp-btn-div text-center">
        @Html.ActionLink("Предпроизводство", "Index", "Предпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Съёмочный период", "Index", "Съёмочный_период", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Постпроизводство", "Index", "Постпроизводство", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Титры и субтитры", "Index", "Титры_и_субтитры", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Тиражирование", "Index", "Тиражирование", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Фильмы", "Index", "Фильм", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
        <br>
        @Html.ActionLink("Сотрудники", "Index", "Сотрудник", null, htmlAttributes: new { @class = "btn btn-info btn-lg active" })
    </div>
</body>
</html>

lab1/CinemaStudio/CinemaStudio/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Very Home Page";
}

<div class="text-center">
    <div class="jumbotron">
        <h1>Добро пожаловать!</h1
    </div>

    <div class="row">
        <div class="col-md-6">
            <h4>Курсовая работа по теме:<br>"Автоматизированная система киностудии"</h4>
        </div>
        <div class="col-md-6">
            <h4>Студент: Шаталов Александр Владимирович
            <br>
            Группа: ИСТбд-31</h4>
        </div>
    </div>
</div>

lab1/CinemaStudio/CinemaStudio/Views/Home/SignInPage.cshtml
@{
    ViewBag.Title = "Вход";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <div class="hp-btn-div">
            <row class="sPage">
                <div class="col-md-4">
                    @Html.ActionLink("Войти как клиент", "Client", "Home", null, htmlAttributes: new { @class = "btn btn-primary btn btn-dark btn-lg active hp-btn" })
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Войти как сотрудник", "Employee", "Home", null, htmlAttributes: new { @class = "btn btn-primary btn btn-dark btn-lg active hp-btn" })
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Войти как администратор", "Administrator", "Home", null, htmlAttributes: new { @class = "btn btn-primary btn btn-dark btn-lg active hp-btn" })
                </div>
            </row>
        </div>
    </div>
</body>
</html>